const CartActionType = {
    FETCH_CART_ITEMS: 'FETCH_CART_ITEMS',
    FETCH_CART_ITEMS_SUCCESS: 'FETCH_CART_ITEMS_SUCCESS',
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART'
}

export default CartActionType;